#FROM microsoft/aspnetcore
#WORKDIR /app
#COPY /app .
#ENTRYPOINT ["dotnet", "Demo2App.dll"]
FROM mcr.microsoft.com/dotnet/core/sdk:2.2 AS build
WORKDIR /app

# copy csproj and restore as distinct layers
COPY *.sln .
COPY Demo2App/*.csproj ./Demo2App/
RUN dotnet restore

# copy everything else and build app
COPY Demo2App/. ./Demo2App/
WORKDIR /app/Demo2App
RUN dotnet publish -c Release -o out


FROM mcr.microsoft.com/dotnet/core/aspnet:2.2 AS runtime
WORKDIR /app
COPY --from=build /app/Demo2App/out ./
EXPOSE 80
ENTRYPOINT ["dotnet", "Demo2App.dll"]